# Generated by Django 3.2.6 on 2021-08-31 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='images/books/%y/%m/%d')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('author_avatar', models.ImageField(blank=True, null=True, upload_to='images/authors/%y/%m/%d')),
                ('pages_num', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rental_day_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rental_period_by_day', models.IntegerField(blank=True, null=True)),
                ('total_rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Rented', 'Rented')], max_length=50, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.category')),
            ],
        ),
    ]
